#Keep all the biolink classes as constants to keep from having to handle name changes.
# of course bigger changes will require code changes as well.

ACTIVITY = 'biolink:Activity'
AGENT = 'biolink:Agent'
ANATOMICAL_ENTITY = 'biolink:AnatomicalEntity'
BIOLOGICAL_PROCESS = 'biolink:BiologicalProcess'
CELL = 'biolink:Cell'
CELLULAR_COMPONENT = 'biolink:CellularComponent'
CHEMICAL_ENTITY = 'biolink:ChemicalEntity'
CHEMICAL_MIXTURE = 'biolink:ChemicalMixture'
COMPLEX_CHEMICAL_MIXTURE = 'biolink:ComplexMolecularMixture'
DEVICE = 'biolink:Device'
DISEASE = 'biolink:Disease'
DRUG = 'biolink:Drug'
FOOD = 'biolink:Food'
GENE = 'biolink:Gene'
GENE_OR_GENE_PRODUCT = 'biolink:GeneOrGeneProduct'
GENE_FAMILY = 'biolink:GeneFamily'
GROSS_ANATOMICAL_STRUCTURE = 'biolink:GrossAnatomicalStructure'
MACROMOLECULAR_COMPLEX = 'biolink:MacromolecularComplexMixin'
MOLECULAR_ACTIVITY = 'biolink:MolecularActivity'
MOLECULAR_MIXTURE = 'biolink:MolecularMixture'
ORGANISM_TAXON = 'biolink:OrganismTaxon'
PATHWAY = 'biolink:Pathway'
PHENOTYPIC_FEATURE = 'biolink:PhenotypicFeature'
PHYSICAL_ENTITY = 'biolink:PhysicalEntity'
POLYPEPTIDE = 'biolink:Polypeptide'
PROCEDURE = 'biolink:Procedure'
PROTEIN = 'biolink:Protein'
PUBLICATION = 'biolink:Publication'
SMALL_MOLECULE = 'biolink:SmallMolecule'
