#Keep all the biolink classes as constants to keep from having to handle name changes.
# of course bigger changes will require code changes as well.

ANATOMICAL_ENTITY = 'biolink:AnatomicalEntity'
GROSS_ANATOMICAL_STRUCTURE = 'biolink:GrossAnatomicalStructure'
CELL = 'biolink:Cell'
CELLULAR_COMPONENT = 'biolink:CellularComponent'
GENE = 'biolink:Gene'
PROTEIN = 'biolink:Protein'
GENEORPROTEIN = 'biolink:GeneOrGeneProduct'
DISEASE = 'biolink:Disease'
PHENOTYPIC_FEATURE = 'biolink:PhenotypicFeature'
BIOLOGICAL_PROCESS = 'biolink:BiologicalProcess'
MOLECULAR_ACTIVITY = 'biolink:MolecularActivity'
PATHWAY = 'biolink:Pathway'
SMALL_MOLECULE='biolink:SmallMolecule'
MOLECULAR_MIXTURE='biolink:MolecularMixture'
CHEMICAL_ENTITY='biolink:ChemicalEntity'
ORGANISM_TAXON='biolink:OrganismTaxon'
POLYPEPTIDE='biolink:Polypeptide'
GENE_FAMILY='biolink:GeneFamily'
COMPLEX_CHEMICAL_MIXTURE='biolink:ComplexMolecularMixture'
CHEMICAL_MIXTURE='biolink:ChemicalMixture'
MACROMOLECULAR_COMPLEX='biolink:MacromolecularComplexMixin'
