# CURIE prefixes used in Babel
#
# The point here is to keep prefixes in one place so that we can easily deal with things like PUBCHEM->PUBCHEM.COMPOUND
# In principle, we should generate this off of the context file?

MESH = "MESH"
NCIT = "NCIT"
CL = "CL"
CLO = "CLO"
GO = "GO"
FMA = "FMA"
UBERON = "UBERON"
SNOMEDCT = "SNOMEDCT"
OMIM = "OMIM"
OMIMPS = "OMIM.PS"
ENSEMBL = "ENSEMBL"
NCBIGENE = "NCBIGene"
WORMBASE = "WormBase"
MGI = "MGI"
ZFIN = "ZFIN"
DICTYBASE = "dictyBase"
WORMBASE = "WormBase"
FLYBASE = "FB"
RGD = "RGD"
SGD = "SGD"
POMBASE = "POMBASE"
KEGG = "KEGG"
KEGGGENE = "KEGG.GENE"
KEGGDISEASE = "KEGG.DISEASE"
KEGGPATHWAY = "KEGG.PATHWAY"
KEGGREACTION = "KEGG.REACTION"
HGNC = "HGNC"
UMLS = "UMLS"
RXCUI = "RXCUI"
NCIT = "NCIT"
PR = "PR"
UNIPROTKB = "UniProtKB"
MONDO = "MONDO"
DOID = "DOID"
OIO = "OIO"
ORPHANET = "orphanet"
GARD = "GARD"  # NCATS Genetic and Rare Diseases rare-disease registry from https://rarediseases.info.nih.gov/
HP = "HP"
EMAPA = "EMAPA"
MP = "MP"
MEDDRA = "MEDDRA"
EFO = "EFO"
ICD9 = "ICD9"
ICD10 = "ICD10"
ICD10CM = "ICD10CM"
ICD0 = "ICD0"
# Lower case to match biolink:Disease's id_prefixes, which spell it "icd11" (as does the existing
# ICD11FOUNDATION below) -- note that biolink_model_prefix_map.json has no ICD-11 entry at all, so
# the prefix map is not the thing to check here. The data spells it "ICD11:", and Text.recurie()
# rewrites that to "icd11:" via Text.prefixmap; that is the intended normalization, and it does not
# change what survives write_compendium(), which buckets identifiers by upper-cased prefix.
ICD11 = "icd11"
RHEA = "RHEA"
EC = "EC"
PANTHERPATHWAY = "PANTHER.PATHWAY"
SMPDB = "SMPDB"
REACT = "REACT"
WIKIPATHWAYS = "WIKIPATHWAYS"
WIKIDATA = "WIKIDATA"
TCDB = "TCDB"
PUBCHEMCOMPOUND = "PUBCHEM.COMPOUND"
CHEMBLCOMPOUND = "CHEMBL.COMPOUND"
UNII = "UNII"
CHEBI = "CHEBI"
DRUGBANK = "DRUGBANK"
CAS = "CAS"
DRUGCENTRAL = "DrugCentral"
GTOPDB = "GTOPDB"
HMDB = "HMDB"
KEGGCOMPOUND = "KEGG.COMPOUND"
KEGGGLYCAN = "KEGG.GLYCAN"
KEGGDRUG = "KEGG.DRUG"
KEGGDGROUP = "KEGG.DGROUP"
KEGGENVIRON = "KEGG.ENVIRON"
CHEMBANK = "ChemBank"
AEOLUS = "Aeolus"
PHARMGKB_DRUG = "PHARMGKB.DRUG"
BIGG_METABOLITE = "BIGG.METABOLITE"
FOODB_COMPOUND = "foodb.compound"
PUBCHEMSUBSTANCE = "PUBCHEM.SUBSTANCE"
SIDERDRUG = "SIDER.DRUG"
INCHI = "INCHI"
INCHIKEY = "INCHIKEY"
NCBITAXON = "NCBITaxon"
HGNCFAMILY = "HGNC.FAMILY"
PANTHERFAMILY = "PANTHER.FAMILY"
COMPLEXPORTAL = "ComplexPortal"
ICD11FOUNDATION = "icd11.foundation"

PMID = "PMID"
DOI = "doi"
PMC = "PMC"
