#The point here is to keep prefixes in one place so that we can easily deal with things like PUBCHEM->PUBCHEM.COMPOUND
# In principle, we should generate this off of the context file?

MESH = 'MESH'
NCIT = 'NCIT'
CL = 'CL'
GO = 'GO'
UBERON = 'UBERON'
SNOMEDCT= 'SNOMEDCT'
OMIM = 'OMIM'
ENSEMBL = 'ENSEMBL'
NCBIGENE = 'NCBIGene'
WORMBASE = 'WormBase'
MGI ='MGI'
ZFIN='ZFIN'
DICTYBASE='dictyBase'
WORMBASE='WormBase'
FLYBASE='FB'
RGD='RGD'
SGD='SGD'
POMBASE='POMBASE'
KEGGGENE='KEGG.GENE'
HGNC='HGNC'
UMLS = 'UMLS'
PR = 'PR'
UNIPROTKB = 'UniProtKB'
